# Generated by Django 4.2 on 2025-05-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=50)),
                ('usuario_apellidos', models.CharField(max_length=120)),
                ('usuario_email', models.EmailField(max_length=254)),
                ('usuario_password', models.CharField(max_length=255)),
                ('usuario_status', models.BooleanField(default=True)),
                ('usuario_fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_rol',
            fields=[
                ('ur_id', models.AutoField(primary_key=True, serialize=False)),
                ('ur_rolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.rol')),
                ('ur_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.usuario')),
            ],
        ),
    ]
