# Generated by Django 4.2 on 2025-05-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
