# Generated by Django 4.2 on 2025-05-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_usuario_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
    ]
