# Generated by Django 4.2 on 2025-05-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_usuario_usuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('mem_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_membresia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.membresia'),
        ),
    ]
