# Generated by Django 4.2 on 2025-05-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_membresia_usuario_usuario_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('tm_id', models.AutoField(primary_key=True, serialize=False)),
                ('tm_nombre', models.CharField(max_length=50)),
                ('tm_precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tm_duracion_dias', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='mem_nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_membresia',
        ),
        migrations.AddField(
            model_name='membresia',
            name='mem_fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='mem_fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='mem_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membresia',
            name='mem_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.usuario'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='mem_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.tipomembresia'),
        ),
    ]
