# Generated by Django 4.2 on 2025-05-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_tipomembresia_remove_membresia_mem_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenadorInfo',
            fields=[
                ('entrenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gym.usuario')),
                ('especialidad', models.CharField(max_length=100)),
                ('dias_disponibles', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
