# Generated by Django 4.2 on 2025-05-26 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_entrenadorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('ue_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gym.usuario')),
                ('ue_entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenador', to='gym.usuario')),
            ],
            options={
                'unique_together': {('ue_cliente', 'ue_entrenador')},
            },
        ),
    ]
