# Generated by Django 4.2 on 2025-05-26 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_usuarioentrenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.PositiveIntegerField(help_text='En centímetros')),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'usuario_rol__ur_rolId': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='avances_como_cliente', to='gym.usuario')),
                ('entrenador', models.ForeignKey(blank=True, limit_choices_to={'usuario_rol__ur_rolId': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_asignados', to='gym.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
